[package]
name = "tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
vercel_runtime = "1.1.6"
tokio = { version = "1", features = ["macros"] }

[[bin]]
name = "tutorial"
path = "api/handler.rs"